formatter: markdown table

#version:

#header-from: main.tf
#footer-from: ""

recursive:
  enabled: false
  path: modules/aws

sections:
  hide:
    - data-sources
  #show: []

#content: ""

output:
  file: README.md
  mode: inject

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
